### PR TITLE
initial setup 3rd party JS lib

### PR DESCRIPTION
**Pull request by hhzl**
Add example with snap.svg JS library. Copied from https://github.com/hhzl/Amber-snapsvg-demo

### CODE REVIEW

**Comment by philippeback** [comment]
Very cool stuff.

**Comment by herby** [comment]
But probably very quickly made slightly incorrect in favour of imports. Though the changes will be minimal.

Philippe Back wrote:

**Comment by hhzl** [comment]
@herby which changes do I need to do for 0.14.3?

**Comment by herby** [comment]
add 'snap.svg' to imports section of your app package itself (in Helios, when selecting package), and removing it from 'deploy.js'.

**Comment by herby** [comment]
and of course, retrofitting the recipe (there is no need for 'add it to deploy.js', but part 'add it to imports and commit a package' is needed to be added).

**Comment by hhzl** [comment]
@herby, I'll do the move to 0.14.3 with a separate issue.

**Pull request merged**
